### ISSUE TITLE
Externally hosted Ollama?

### ISSUE THREAD

**Issue by Natfan** [mezbaul-h/june#5]
Hi there,

I haven't installed this project yet, but it looks very interesting. I do have one question: is it possible to point the project to use another endpoint for the Ollama API? I have an endpoint existing on my network (gpt.domain.com) which I use for local LLM inference, and was wondering if I could point june to that domain as well?

Thanks,
-nat

**Comment by mezbaul-h** [comment]
Yeah, absolutely. Set the `OLLAMA_HOST` environment variable and try. For example:

```shell
OLLAMA_HOST=http://localhost:11434 june-va
```
