### ISSUE TITLE
Gradio demo

### ISSUE THREAD

**Issue by abidlabs** [mezbaul-h/june#6]
This is really incredible work! I'd love to try this and I'm wondering whether you've considered making a simple web ui that can be run locally, e.g. with [gradio](https://github.com/gradio-app/gradio/)? Happy to help if there's interest!

**Comment by mezbaul-h** [comment]
That's a wonderful proposal! Gradio is indeed amazing, I've actually used it before for some of my other projects which were more straightforward. I haven't really dived deep into its advanced features though so I'm not entirely sure if the streaming audio functionality would be possible to achieve with it. I'd absolutely love to have your help on this!

**Comment by dawoodkhan82** [comment]
@mezbaul-h Currently working on a gradio demo. Will keep you posted!

**Comment by ElhamAhmedian** [comment]
Any update on this? Thanks
