### ISSUE TITLE
Mac OS M series portaudio fails to install via pip install .

### ISSUE THREAD

**Issue by gshipley** [mezbaul-h/june#8]
For Mac OS, it might be worth mentioning in the install instructions to run the following command before doing the pip install:

brew install portaudio

---------

Building wheel for PyAudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for PyAudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.0-arm64-cpython-311
      creating build/lib.macosx-14.0-arm64-cpython-311/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.macosx-14.0-arm64-cpython-311/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.macosx-14.0-arm64-cpython-311
      creating build/temp.macosx-14.0-arm64-cpython-311/src
      creating build/temp.macosx-14.0-arm64-cpython-311/src/pyaudio
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Users/gshipley/code/june/venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/pyaudio/device_api.c -o build/temp.macosx-14.0-arm64-cpython-311/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyAudio
  Building wheel for encodec (pyproject.toml) ... done
  Created wheel for encodec: filename=encodec-0.1.1-py3-none-any.whl size=45759 sha256=3bdaa78e2da3053e4a29b4239ea2b742f7b2bbd482fd92f417d9a6b649868863
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/b4/a4/88/480018a664e58ca7ce6708759193ee51b017b3b72aa3df8a85
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13707 sha256=4934c972d843498ca5bbfa2eff83f3a3c999f8356d3bc95b4e7862561988f8b7
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/1a/b0/8c/4b75c4116c31f83c8f9f047231251e13cc74481cca4a78a9ce
  Building wheel for gruut-ipa (pyproject.toml) ... done
  Created wheel for gruut-ipa: filename=gruut_ipa-0.13.0-py3-none-any.whl size=104871 sha256=47a25236fd5ada7959cd4b4600fd74b5cc95cff7921bd33dec6a013cded15c63
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/c7/10/89/a5908dd7a9a032229684b7679396785e19f816667f788087fb
  Building wheel for gruut-lang-de (pyproject.toml) ... done
  Created wheel for gruut-lang-de: filename=gruut_lang_de-2.0.0-py3-none-any.whl size=18498181 sha256=dbe5e807edbb0b0080307c21d6395bb28e77d0184427d0bf0031b4d4ad8944e6
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/c4/ad/f3/eecf61483881d7a8a83ece48eeaf9ee3ad202ccb530863d9e5
  Building wheel for gruut-lang-en (pyproject.toml) ... done
  Created wheel for gruut-lang-en: filename=gruut_lang_en-2.0.0-py3-none-any.whl size=15297176 sha256=e0eedd3eee7e608d2b5866ce7c8d81712637b656ab772a6653810efdb84b123e
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/e2/78/bd/1d87e79fe8b770d31295d9340cc05bc16ddb892d0bae94a58b
  Building wheel for gruut-lang-es (pyproject.toml) ... done
  Created wheel for gruut-lang-es: filename=gruut_lang_es-2.0.0-py3-none-any.whl size=32173793 sha256=0ffdfa52d7b377a918560bea86a233db5f27d06399392bc9eb23f363a33f5d15
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/7e/80/02/78d177dbdf2925c013cb935a430e98930b399e817c83586bbc
  Building wheel for gruut-lang-fr (pyproject.toml) ... done
  Created wheel for gruut-lang-fr: filename=gruut_lang_fr-2.0.2-py3-none-any.whl size=10968766 sha256=b6e472e0d17f375be22719b0f5929745313e5632eb9d7eb06c58738de04e8c82
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/e0/e7/a0/7c416a3eeaa94ca71bf7bcbc6289cced2263d8ba35e82444bb
  Building wheel for python-crfsuite (pyproject.toml) ... done
  Created wheel for python-crfsuite: filename=python_crfsuite-0.9.10-cp311-cp311-macosx_14_0_arm64.whl size=171939 sha256=01c71de5dc69dff0536a3c6349798d4b1bf677d70d61438431bfe58d471c7401
  Stored in directory: /Users/gshipley/Library/Caches/pip/wheels/c0/a0/14/86127d22cfcc7f72987d6a9c3f7baa22da0d8f70303600cd01
Successfully built june-va coqui-tts gruut encodec docopt gruut-ipa gruut-lang-de gruut-lang-en gruut-lang-es gruut-lang-fr python-crfsuite
Failed to build PyAudio
ERROR: Could not build wheels for PyAudio, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip

 gshipley  …/june   master   v3.11.9  
 pip3 install pyaudio
Collecting pyaudio
  Using cached PyAudio-0.2.14.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.0-arm64-cpython-311
      creating build/lib.macosx-14.0-arm64-cpython-311/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.macosx-14.0-arm64-cpython-311/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.macosx-14.0-arm64-cpython-311
      creating build/temp.macosx-14.0-arm64-cpython-311/src
      creating build/temp.macosx-14.0-arm64-cpython-311/src/pyaudio
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Users/gshipley/code/june/venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/pyaudio/device_api.c -o build/temp.macosx-14.0-arm64-cpython-311/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
Failed to build pyaudio
ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects

**Comment by tamarit** [comment]
I've solved it using [this](https://stackoverflow.com/a/76002143)
